### ISSUE TITLE
Invalid Frame Resolution Error

### ISSUE THREAD

**Issue by ShabnamR** [krontech/chronos-examples#2]
The example in the folder for changing the resolution constantly gives Invalid Frame Resolution Error for any combination hRes and vRes. Is there a way getting it to work?

**Comment by sanjpm** [comment]
Which example language are you working with?

**Comment by ShabnamR** [comment]
Python, I was able to make it work for some of the resolutions, but not all.

**Comment by sanjpm** [comment]
I see. There are a few constraints to adjusting the resolution, since the settings must be compatible with the image sensor's windowing modes, so:

hRes must be adjusted in increments of 16 pixels for a Chronos 1.4, or 32 pixels for a Chronos 2.1.
vRes must be adjusted in increments of 2 pixels for both cameras.

Let me know if that helps, or whether the issue persists, thanks!

**Comment by ShabnamR** [comment]
Yes, I tried this and it worked. 

Is there any way for the camera to recognize the pixels not in the correct increments and set it to the closest value? When entering on the camera LCD it does it automatically. I wonder if I should just place an if clause of my own to to do this check, or is there an automated way of doing this? 

Thanks for the help!

**Comment by sanjpm** [comment]
The best way would be to implement the checks in your own code. Since the GUI that is shown on the LCD is open source, you can see how the camera does it here: https://github.com/krontech/chronos-cam-app/blob/575bc2676814f7bf8f4ce64e6c2435c22e588f5d/src/recsettingswindow.cpp#L44 although we rely on some built-ins from the Qt framework.

**Comment by ShabnamR** [comment]
Sorry for the delay, I just realized I never closed this, but thanks to the help we got it working. Thanks!
